Vagrant.configure("2") do |config|
  config.vm.define "utm_ubuntu" do |utm_vm|
    utm_vm.vm.box = "virtualbox" # Placeholder, since no box will be downloaded
    utm_vm.vm.hostname = "utm-ubuntu"

    # SSH configuration to connect to the VM
    utm_vm.vm.network "public_network", ip: "192.168.64.2" # Replace with your VM IP
    utm_vm.ssh.host = "192.168.64.2" # Replace with your VM IP
    utm_vm.ssh.username = "ubuntu" # Replace with your VM username
    utm_vm.ssh.password = "ubuntu" # Or configure SSH keys
    utm_vm.ssh.port = 22
  end
end